### ISSUE TITLE
How to install Radiance on my Mac system？

### ISSUE THREAD

**Issue by ChenWenQian** [NREL/Radiance#24]
I'd like to Know that how to install Radiance on the OSX system？and how to run the programs?
I am not familiar with all the environment variable or path thing.  

If anyone is familiar with the installation , please elaborate the procedures,  Great thanks.

**Comment by sariths** [comment]
Not a Mac user, however, this response from Rob Guglielmetti should still be useful:
https://www.radiance-online.org:447/pipermail/radiance-general/2015-September/011264.html

The video Rob refers to in his response is probably not available any more, however, you will be to find a guide for setting PATH and other environment variables through a simple google search.

Tutorials for Radiance are here: https://www.radiance-online.org/learning/tutorials

**Comment by ChenWenQian** [comment]
@sariths Thank you for your help, I set the environment , but it occurs this error "rtrace: system - cannot find function file "rayinit.cal": No such file or directory".  I don't know why ?

**Comment by sariths** [comment]
This is likely because the RAYPATH variable was not assigned correctly. Rtrace looks for rayinit.cal inside the lib directory specified through RAYPATH. What do you get when you type the command `echo $RAYPATH` in the terminal window?

It should be something like this (In my system the lib directory is .../work/rad/lib):
![image](https://user-images.githubusercontent.com/10361848/38088727-23a2478c-335d-11e8-8933-64de4a3b6090.png)

**Comment by rpg777** [comment]
Hi folks, sorry I just saw this. It's true, the NREL mac and linux packages do not automatically set the PATH and RAYPATH env vars for you. Here is what I have in my `~/.bash_profile` file (a quick Google search will yield leads on how to edit this file):

```
## Radiance path crap
export PATH=$PATH:.:/usr/local/radiance/bin
export RAYPATH=.:/usr/local/radiance/lib
export MANPATH=$MANPATH:/usr/local/radiance/man
```
