### ISSUE TITLE
How to run objpict and objview on windows?

### ISSUE THREAD

**Issue by redinkinc** [NREL/Radiance#4]
Hi, I'm new to randiance (Version 4.2.2, win32) and currently trying to run some examples I found on the internet. Sometimes there is a need to run objpict oder objview, which both seem to be perl files. How can I run them properly on windows? Sometimes I find some cmds running objline, which is missing in my bin file. Have I to install this seperately? 
Thanks, Fabian

**Comment by mostaphaRoudsari** [comment]
Hi @redinkinc, You need to install perl on your machine. There are a couple of different options. Here is one of the discussions about running perl scripts on Windows: http://www.radiance-online.org:82/pipermail/radiance-general/2014-July/010411.html

**Comment by redinkinc** [comment]
@mostaphaRoudsari: Thanks for the quick reply. Now I'm using strawberry Perl and everything is working. But "objline" is still missing and I also am missing "cat" and "ximage". Do you know how to run them on windows?
Thanks, Fabian

**Comment by mostaphaRoudsari** [comment]
@redinkinc as far as I remember they are not part of the Windows binding but @rpg777 is the one who really knows the answer to this question.

**Comment by rpg777** [comment]
Oh wow, folks are using this repo for comments and issues? This is awesome. Since this issue is related to the NREL packages I suppose this is the best spot for this post, but any Radiance/development related issues we should probably go on UnmetHours or the radiance-general listserv.

OK so replace ```cat``` with ```type``` and you should be all set there. That's just an operating system difference in naming of the same basic utility (in this case a concatenator).  @mostaphaRoudsari is right, ```ximage``` is not built on Windows because it uses the X11 display driver. I believe that is why objline is not included on Windows either. Sorry!! To view your hdrs I suggest you convert them to TIFF (using ```ra_tiff```) and then either convert to jpg or png or view them directly with a TIFF viewer (which I ASSume exist for Windows).

**Comment by redinkinc** [comment]
yes, everything works fine now. Big thanks @rpg777!

**Comment by rpg777** [comment]
Excellent. Any reason why you're not using a more recent Radiance version? We have installers for v5.0.a here...

**Comment by redinkinc** [comment]
I installed the latest release version just because I didn't see any reasons to install the pre release versions. If you mean there are helpful functionalities and the pre-releases are stable I would have no reason to stay on version 4.2.2...

**Comment by rpg777** [comment]
Yeah I recommend 5.0.a.4 (https://github.com/NREL/Radiance/releases/tag/5.0.a.4). Radiance versioning is a bit misleading. Yes, the .a means "alpha" but it's less bleeding edge that you might expect, and bugs are squashed rapidly. Radiance's main developer is working toward an 5.0 official release as well, shooting for the end of this month, if you want to wait for that. But there is a LOT of new, good stuff (and fixes) in 5.0.a since 4.2.2!
